export type Meal={name:string;food:string;protein:number};
export type Plan={focus:string;calories:number;bed:string;workout:string[];meals:Meal[];coach:string};
const M={
mon:[{name:"Breakfast",food:"2 eggs, 1 cup egg whites, oats and berries",protein:45},{name:"Snack",food:"2 cups nonfat Greek yogurt, berries and chia",protein:42},{name:"Lunch",food:"7 oz chicken breast, rice, broccoli, salsa and avocado",protein:50},{name:"Dinner",food:"6 oz salmon, potato and asparagus",protein:40}],
tue:[{name:"Breakfast",food:"Protein oats: oats, whey, banana and Greek yogurt",protein:42},{name:"Snack",food:"1½ cups low-fat cottage cheese and berries",protein:40},{name:"Lunch",food:"7 oz turkey, quinoa, greens and tomatoes",protein:50},{name:"Dinner",food:"6 oz lean sirloin, sweet potato and green beans",protein:42}],
wed:[{name:"Breakfast",food:"Greek yogurt, whey, berries and oats",protein:52},{name:"Snack",food:"2 eggs and 4 oz turkey breast",protein:38},{name:"Lunch",food:"2 tuna packets, white beans, celery and tomatoes",protein:45},{name:"Dinner",food:"6 oz chicken fajita bowl with rice and vegetables",protein:45}],
thu:[{name:"Breakfast",food:"2 eggs, egg whites, high-fiber tortilla, salsa and fruit",protein:42},{name:"Snack",food:"Whey shake with berries and milk",protein:35},{name:"Lunch",food:"7 oz turkey meatballs, marinara, vegetables and pasta",protein:48},{name:"Dinner",food:"7 oz cod, rice and roasted vegetables",protein:45}],
fri:[{name:"Breakfast",food:"2 eggs, 1 cup cottage cheese and fruit",protein:42},{name:"Snack",food:"2 cups nonfat Greek yogurt and berries",protein:40},{name:"Lunch",food:"7 oz chicken, potato, spinach and tomatoes",protein:50},{name:"Dinner",food:"7 oz 93/7 beef burger, vegetables and potato",protein:45}],
sat:[{name:"Breakfast",food:"2 eggs, egg whites, smoked salmon and toast",protein:45},{name:"Snack",food:"Greek yogurt mixed with whey and berries",protein:42},{name:"Lunch",food:"8 oz shrimp, rice, cucumber, carrots and avocado",protein:50},{name:"Dinner",food:"7 oz pork tenderloin, vegetables and potato",protein:48}],
sun:[{name:"Breakfast",food:"Vegetable omelet with eggs, egg whites and oats",protein:45},{name:"Snack",food:"2 cups Greek yogurt, fruit and cinnamon",protein:40},{name:"Lunch",food:"7 oz chicken high-fiber wrap with greens",protein:50},{name:"Dinner",food:"6 oz salmon, rice, broccoli and cucumber",protein:40}]};
const W={
mon:["30° incline dumbbell press — 4 × 8–10","Flat dumbbell press — 3 × 8–12","Chest-supported row — 4 × 10","Low-to-high fly — 3 × 12–15","Lateral raise — 3 × 15","Pallof press — 3 × 10/side"],
tue:["Zone 2 bike or brisk walk — 30–35 min","90/90 breathing — 5 breaths","Dead bug — 3 × 8/side","Glute bridge — 3 × 12","Wall slide + face pull — 3 × 12","Hip-flexor and calf stretch"],
wed:["Goblet squat — 4 × 8–10","Split squat — 3 × 8/side","Hip thrust — 4 × 10–12","Hamstring curl — 3 × 12","Suitcase carry — 3 × 40 sec/side","Easy bike cooldown — 10 min"],
thu:["Brisk walk — 35–40 min","Posture reset — 10 min","McGill Big 3 — 2 rounds","Pec, lat, calf and hip-flexor stretch","No extra hard training"],
fri:["PT is the main session","Prioritize trunk control, glutes, upper back and hip mobility","No second lift","Recovery meal: 35–50 g protein plus carbs","Easy walk only if restorative"],
sat:["Flat dumbbell press — 4 × 6–10","Slight-incline press — 3 × 10–12","One-arm row — 4 × 10/side","Chest-height fly — 3 × 12–15","Feet-elevated push-up — 2 clean sets","Dead bug — 3 × 8/side"],
sun:["Easy walk or bike — 35–45 min","Posture reset — 10 min","McGill Big 3 — 2 rounds","Meal prep for Monday","Optional 20–30 min nap before 3 PM"]};
const MAP=[["Sunday","Recovery + Alignment",2050,"8:45 PM","sun"],["Monday","Chest + Upper Body",2200,"8:45 PM","mon"],["Tuesday","Zone 2 + Alignment",2100,"8:45 PM","tue"],["Wednesday","Lower Body Athletic",2250,"8:45 PM","wed"],["Thursday","Recovery + Mobility",2050,"8:45 PM","thu"],["Friday","PT + Recovery",2200,"9:30 PM","fri"],["Saturday","Chest + Full Body",2250,"9:30 PM","sat"]] as const;
export const START=new Date(2026,6,18);
export const DAYS=Array.from({length:30},(_,i)=>{const date=new Date(START);date.setDate(START.getDate()+i);const row=MAP[date.getDay()],key=row[4] as keyof typeof M;const phase=i<7?"Foundation":i<14?"Build":i<22?"Push":"Reveal";let workout=[...W[key]];let focus:string=row[1];if(i===0)workout=["Record morning weight and front, side and back photos",...workout];if(i===14)workout=["Midpoint weight, waist and photos",...workout];if(i===29){focus="Final Reveal";workout=["Morning weight, waist and final photos","Easy walk — 40 min","Posture reset — 10 min","Normal water and sodium","Review Day 1 vs Day 30"];}return{day:i+1,date,phase,focus,calories:row[2],bed:row[3],workout,meals:M[key],coach:i<7?"Win the basics. No bonus punishment.":i<14?"Add a rep or small load only when form stays clean.":i<22?"Push performance while keeping one rep in reserve.":"Keep muscle, reduce fatigue and let the work show."} satisfies Plan&{day:number;date:Date;phase:string};});
export const BASELINE={weight:176.2,bodyFat:20.6,muscle:132.8,lean:139.8,visceral:9,readiness:85,sleep:84,activity:88};
export const CHEST_A=["30° incline dumbbell press — 4 × 6–10","Flat dumbbell press — 3 × 8–12","Low-to-high fly — 3 × 12–15","Push-up with hard squeeze — 2 clean sets","Face pull — 3 × 15"];
export const CHEST_B=["Flat dumbbell press — 4 × 6–10","Slight-incline dumbbell press — 3 × 10–12","Chest-height fly — 3 × 12–15","Feet-elevated push-up — 2 clean sets","Chest-supported row — 4 × 10–12"];
