"use client";
import {useEffect,useRef,useState} from "react";
import styles from "./Transform.module.css";
import {BASELINE,CHEST_A,CHEST_B,DAYS,START} from "./plan";
type Tab="today"|"plan"|"progress"|"chest";type Check={weight:string;waist:string;bodyFat:string;sleep:string;readiness:string;energy:string;soreness:string;notes:string};
const EMPTY:Check={weight:"",waist:"",bodyFat:"",sleep:"",readiness:"",energy:"",soreness:"",notes:""},STORE="vitalis-transform-v3",PHOTOS=["front","side","back"] as const;
const PHOTOSETS=[{label:"Day 1",src:["/transform-photos/day1-front.jpg","/transform-photos/day1-side.jpg","/transform-photos/day1-back.jpg"]},{label:"Day 3",src:["/transform-photos/day3-front.jpg","/transform-photos/day3-side.jpg","/transform-photos/day3-back.jpg"]}];
function idxToday(){const n=new Date(),a=new Date(n.getFullYear(),n.getMonth(),n.getDate()).getTime(),b=new Date(START.getFullYear(),START.getMonth(),START.getDate()).getTime();return Math.max(0,Math.min(29,Math.floor((a-b)/86400000)))}
function status(c:Check){const s=+c.sleep||84,r=+c.readiness||85,e=+c.energy||7,o=+c.soreness||2;if(r<68||s<65||e<4||o>7)return"Red";if(r<75||s<75||e<6||o>5)return"Yellow";return"Green"}
function resize(file:File):Promise<string>{return new Promise((ok,fail)=>{const rd=new FileReader();rd.onload=()=>{const im=new Image();im.onload=()=>{const k=Math.min(1,900/Math.max(im.width,im.height)),cv=document.createElement("canvas");cv.width=Math.round(im.width*k);cv.height=Math.round(im.height*k);cv.getContext("2d")!.drawImage(im,0,0,cv.width,cv.height);ok(cv.toDataURL("image/jpeg",.72))};im.onerror=fail;im.src=rd.result as string};rd.onerror=fail;rd.readAsDataURL(file)})}
export default function TransformApp(){
 const[tab,setTab]=useState<Tab>("today"),[day,setDay]=useState(0),[done,setDone]=useState<Record<string,boolean>>({}),[checks,setChecks]=useState<Record<string,Check>>({}),[photos,setPhotos]=useState<Record<string,string>>({}),[ready,setReady]=useState(false);const touch=useRef(0),plan=DAYS[day],check=checks[day]||EMPTY,mode=status(check);
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem(STORE)||"{}");setDay(s.day??idxToday());setDone(s.done||{});setChecks(s.checks||{});setPhotos(s.photos||{})}catch{setDay(idxToday())}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(STORE,JSON.stringify({day,done,checks,photos}))},[ready,day,done,checks,photos]);
 const total=DAYS.reduce((n,d)=>n+d.workout.length+4,0),completed=Object.values(done).filter(Boolean).length,pct=Math.round(completed/total*100),toggle=(k:string)=>setDone(v=>({...v,[k]:!v[k]})),setCheck=(k:keyof Check,v:string)=>setChecks(x=>({...x,[day]:{...(x[day]||EMPTY),[k]:v}})),nav=(n:number)=>setDay(Math.max(0,Math.min(29,n)));
 const coach=mode==="Green"?"Full plan. Train with intent.":mode==="Yellow"?"Remove one set from each lift and skip finishers.":"Walk, mobility and McGill Big 3 only.";
 async function addPhoto(k:string,f?:File){if(f)setPhotos(p=>({...p,[k]:await resize(f)}))}
 return <main className={styles.root}>
  <header className={styles.header}><div><div className={styles.eyebrow}>Matthew · 30 days</div><h1 className={styles.title}>Transformation</h1></div><div className={styles.phase}>{mode}</div></header>
  <section className={styles.progressArea}><div className={styles.progressMeta}><span>{completed} of {total} complete</span><span>{pct}%</span></div><div className={styles.progressTrack}><div className={styles.progressFill} style={{width:`${pct}%`}}/></div></section>
  <nav className={styles.tabs}>{(["today","plan","progress","chest"] as Tab[]).map(t=><button key={t} onClick={()=>setTab(t)} className={`${styles.readinessButton} ${tab===t?styles.readinessActive:""}`}>{t[0].toUpperCase()+t.slice(1)}</button>)}</nav>
  <section className={styles.viewport}><div className={styles.slide} onTouchStart={e=>touch.current=e.changedTouches[0].clientX} onTouchEnd={e=>{const x=e.changedTouches[0].clientX-touch.current;if(tab==="plan"&&Math.abs(x)>55)nav(day+(x<0?1:-1))}}>
   {tab==="today"&&<><div className={styles.dayTop}><div><div className={styles.date}>Day {plan.day} · {plan.date.toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"})}</div><h2 className={styles.focus}>{plan.focus}</h2></div><div className={styles.phase}>{plan.phase}</div></div><div className={styles.metrics}><Metric a="Calories" b={`${plan.calories}`}/><Metric a="Protein" b="170 g"/><Metric a="Water" b="100 oz"/></div>
    <Panel title="Coach"><p className={styles.smallText}>{coach} {plan.coach}</p></Panel>
    <Panel title="Morning check-in"><div className={styles.macroGrid}>{(["weight","waist","bodyFat","sleep","readiness","energy","soreness"] as (keyof Check)[]).map(k=><label className={styles.macro} key={k}><span>{k.replace(/([A-Z])/g," $1")}</span><input className={styles.input} value={check[k]} onChange={e=>setCheck(k,e.target.value)} inputMode="decimal"/></label>)}</div><textarea className={styles.textarea} value={check.notes} onChange={e=>setCheck("notes",e.target.value)} placeholder="Energy, mood, pain, notes…"/></Panel>
    <Checklist title="Today's mission" items={plan.workout} prefix={`${day}:w`} done={done} toggle={toggle}/><Meals day={day} done={done} toggle={toggle}/></>}
   {tab==="plan"&&<><Heading plan={plan}/><Panel title="Training">{plan.workout.map((x,i)=><Row key={x} n={`${i+1}`} text={x}/>)}</Panel><Panel title="High-protein meals">{plan.meals.map(m=><Row key={m.name} n={`${m.protein}`} text={`${m.name} — ${m.food}`}/>)}</Panel></>}
   {tab==="progress"&&<><div className={styles.dayTop}><div><div className={styles.date}>Visual + biometric timeline</div><h2 className={styles.focus}>Progress</h2></div><div className={styles.phase}>{((+check.weight||BASELINE.weight)-BASELINE.weight).toFixed(1)} lb</div></div><div className={styles.metrics}><Metric a="Baseline" b={`${BASELINE.weight}`}/><Metric a="Current" b={check.weight||"—"}/><Metric a="Body fat" b={`${check.bodyFat||BASELINE.bodyFat}%`}/></div>
    {PHOTOSETS.map(set=><Panel title={`${set.label} photos`} key={set.label}><div className={styles.photoGrid}>{set.src.map((src,i)=><figure key={src}><img src={src} alt={`${set.label} ${PHOTOS[i]}`}/><figcaption>{PHOTOS[i]}</figcaption></figure>)}</div></Panel>)}
    <Panel title="Current photos"><div className={styles.photoGrid}>{PHOTOS.map(p=><label key={p} className={styles.photoUpload}>{photos[p]?<img src={photos[p]} alt={p}/>:<span>Add {p}</span>}<input type="file" accept="image/*" hidden onChange={e=>addPhoto(p,e.target.files?.[0])}/></label>)}</div></Panel>
    <Panel title="Baseline"><div className={styles.macroGrid}><Metric a="Muscle" b={`${BASELINE.muscle} lb`}/><Metric a="Lean mass" b={`${BASELINE.lean} lb`}/><Metric a="Readiness" b={`${BASELINE.readiness}`}/><Metric a="Sleep" b={`${BASELINE.sleep}`}/></div></Panel></>}
   {tab==="chest"&&<><div className={styles.dayTop}><div><div className={styles.date}>Twice-weekly priority</div><h2 className={styles.focus}>Fuller Chest</h2></div><div className={styles.phase}>12–16 sets</div></div><Panel title="Session A · Upper fullness">{CHEST_A.map((x,i)=><Row key={x} n={`${i+1}`} text={x}/>)}</Panel><Panel title="Session B · Total thickness">{CHEST_B.map((x,i)=><Row key={x} n={`${i+1}`} text={x}/>)}</Panel><Panel title="Daily posture"><p className={styles.smallText}>Wall slides 2 × 10 · face pulls 2 × 15 · doorway stretch 30 sec/side · 90/90 breathing 5 breaths. Build thickness around the sternum and improve how the rib cage displays the pecs.</p></Panel></>}
  </div></section>
  <footer className={styles.footer}><button className={styles.navButton} disabled={day===0} onClick={()=>nav(day-1)}>← Previous</button><select className={styles.daySelect} value={day} onChange={e=>nav(+e.target.value)}>{DAYS.map((d,i)=><option key={d.day} value={i}>Day {d.day}</option>)}</select><button className={styles.navButton} disabled={day===29} onClick={()=>nav(day+1)}>Next →</button></footer>
 </main>}
function Panel(p:{title:string;children:React.ReactNode}){return <section className={styles.panel}><div className={styles.sectionLabel}>{p.title}</div>{p.children}</section>}
function Metric({a,b}:{a:string;b:string}){return <div className={styles.metric}><span className={styles.metricLabel}>{a}</span><strong className={styles.metricValue}>{b}</strong></div>}
function Row({n,text}:{n:string;text:string}){return <div className={styles.task}><span>{n}</span><span>{text}</span></div>}
function Heading({plan}:{plan:(typeof DAYS)[number]}){return <div className={styles.dayTop}><div><div className={styles.date}>Day {plan.day} of 30</div><h2 className={styles.focus}>{plan.focus}</h2></div><div className={styles.phase}>{plan.phase}</div></div>}
function Checklist({title,items,prefix,done,toggle}:{title:string;items:string[];prefix:string;done:Record<string,boolean>;toggle:(k:string)=>void}){return <Panel title={title}><div className={styles.list}>{items.map((x,i)=>{const k=`${prefix}${i}`;return <label className={`${styles.task} ${done[k]?styles.taskDone:""}`} key={x}><input className={styles.checkbox} type="checkbox" checked={!!done[k]} onChange={()=>toggle(k)}/><span>{x}</span></label>})}</div></Panel>}
function Meals({day,done,toggle}:{day:number;done:Record<string,boolean>;toggle:(k:string)=>void}){return <Panel title="Today's meals"><div className={styles.list}>{DAYS[day].meals.map((m,i)=>{const k=`${day}:m${i}`;return <label className={`${styles.task} ${done[k]?styles.taskDone:""}`} key={m.name}><input className={styles.checkbox} type="checkbox" checked={!!done[k]} onChange={()=>toggle(k)}/><span><b>{m.name} · {m.protein} g</b><br/><span className={styles.smallText}>{m.food}</span></span></label>})}</div></Panel>}
